In [1]:
!pip install faiss-cpu
!pip install sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 16.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 470.2/470.2 kB 12.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.4/515.4 kB 17.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 5.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 4.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 418.4/418.4 kB 5.0 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 6.9 MB/s eta 0:00:0000:0100:01


In [2]:

# import necessary libraries
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [5]:
a = "/Users/arnavbhatnagar/Downloads/sample_text.csv"
df = pd.read_csv(a)
df.shape

(8, 2)

In [6]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [ ]:
#Step 1 : Create source embeddings for the text column

In [9]:
from sentence_transformers import SentenceTransformer

In [8]:
pip install tf-keras

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 8.8 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [10]:
from sentence_transformers import SentenceTransformer

In [11]:
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [12]:
vectors.shape

(8, 768)

In [13]:
dim = vectors.shape[1]
dim

768

In [ ]:
#Step 2 : Build a FAISS Index for vectors

In [14]:
import faiss

index = faiss.IndexFlatL2(dim)

In [ ]:
#Step 3 : Normalize the source vectors (as we are using L2 distance to measure similarity) and add to the index

In [15]:
index.add(vectors)

In [16]:

index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x32ba96550> >

In [ ]:
#Step 4 : Encode search text using same encorder and normalize the output vector

In [17]:
search_query = "I want to buy a polo t-shirt"
# search_query = "looking for places to visit during the holidays"
# search_query = "An apple a day keeps the doctor away"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [18]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [ ]:
#Step 5: Search for similar vector in the FAISS index created

In [24]:
import faiss
import numpy as np

# Example: let's say your index is dimension 128
d = 32
index = faiss.IndexFlatL2(d)

# add some dummy data to the index
vecs = np.random.random((10, d)).astype('float32')
index.add(vecs)

# now define new_vec with same dimension
new_vec = np.random.random((1, d)).astype('float32')

# search for top 2 nearest neighbors
distances, I = index.search(new_vec, k=2)

print(distances)
print(I)


[[2.8780863 4.0622005]]
[[0 2]]


In [25]:
distances, I = index.search(new_vec, k=2)
distances

array([[2.8780863, 4.0622005]], dtype=float32)

In [26]:
I

array([[0, 2]])

In [27]:
I.tolist()

[[0, 2]]

In [28]:
row_indices = I.tolist()[0]
row_indices

[0, 2]

In [29]:
df.loc[row_indices]

text category
0      Meditation and yoga can improve mental health   Health
2  These are the latest fashion trends for this week  Fashion

In [30]:
search_query

'I want to buy a polo t-shirt'